feat(01-building-blocks): added workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,4 +1,4 @@
-name: 01 - Building Blocks
+name: Building Blocks
 
 on: push
 
@@ -8,12 +8,13 @@ jobs:
     steps:
       - name: Say hello
         run: echo "Hello, world"
+
   echo-goodbye:
-     run-on: ubuntu-latest
-     steps:
-       -  name: Failed step
-          run: |
-            echo "I will fail"
-            exit 1
-        - name: Say goodbye
-          run: echo "Goodbye"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say goodbye
+        run: echo "Goodbye"
